apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-rc-v2
spec:
  replicas: 0  #start with zero, then scale up manually
  selector:
    app: nginx
    version: v2
  template:
    metadata:
      labels:
        app: nginx
        version: v2
    spec:
      containers:
      - name: nginx
        image: nginx:1.21
        ports:
        - containerPort: 80

